module.exports = {
  docs: [
    'introduction/getting-started',
    'prd/overview',
    'prd/concepts',
    {
      type: 'category',
      label: '用户',
      items: [{
        type: 'autogenerated',
        dirName: 'prd/user',
      }],
    },
    'prd/hive',
    'prd/containers',
    'prd/pass',
    'prd/frontpage',
  ], 
};
